[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
botan = {version = "*", features = ["botan3"]}
byteorder = "1.5.0"
chrono = "0.4.40"
crossbeam-channel = "0.5.15"
ctrlc = "3.4.6"
dirs = "6.0.0"
rayon = "1.10.0"
shared = { version = "0.1.0", path = "../shared" }
