[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
chrono = "0.4.40"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rand = "0.9.1"
libc = "0.2.172"

[profile.dev]
overflow-checks = false
